### ISSUE TITLE
Update to match with Angular 2 final release 

### ISSUE THREAD

**Issue by codegastudio** [amcharts/amcharts3-angular2#1]
Hello,

Angular 2 has an official release since 16/09/2016.
Could you update your code to use Module instead of Directive ?

Thank you

**Comment by Pauan** [comment]
Hi @codegastudio,

What do you mean? Modules and Directives are different. Directives are used when you need to create an Angular wrapper for existing code, which is exactly what `amcharts3-angular2` does.

**Comment by codegastudio** [comment]
@Pauan Thx to have update your doc to match with angular final release implementation.
Some other chart lib choose to use Module instead of Directive to export their library in components like Chart.js with ng2-charts.
I thought you would have done the same.  
Doesn't matter

**Comment by Pauan** [comment]
@codegastudio I see, `ng2-charts` exports an `NgModule` and the `NgModule` then uses a `Directive` internally. I'll consider doing that, thanks for the suggestion!

**Comment by Pauan** [comment]
@codegastudio Version `1.1.0` of `amcharts3-angular2` now uses `NgModule`, which you can use like this:

```
import { AmChartsModule } from "amcharts3-angular2";

@NgModule({
  imports: [
    AmChartsModule
  ]
})
export class AppModule {}
```

You can upgrade by deleting your `node_modules/amcharts3-angular2` folder and then running `npm install`
