### ISSUE TITLE
Update dependencies to Angular 8

### ISSUE THREAD

**Issue by patrickschroeter** [amcharts/amcharts3-angular2#103]
When using amcharts with the latest Version of Angular you get an error while installing npm packages:

`@amcharts/amcharts3-angular@2.2.3 requires a peer of @angular/core@^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by Pauan** [comment]
Thanks for the report, this has been fixed with `@amcharts/amcharts3-angular2` version `2.2.4`
