### ISSUE TITLE
Ionic 2

### ISSUE THREAD

**Issue by zeljkou** [amcharts/amcharts3-angular2#13]
None of methods on serial chart works. Can't validate or zoom out, any sugestions?

EDIT: Ok this.chart is just config for actual chart. How do I access actual chart so I can use its methods?

Thank you,

Zeljko

**Comment by Pauan** [comment]
@zeljkou I'm very sorry for the delay.

We made some significant changes to the `amcharts3-angular2` plugin.

You will need to [change your code to use the new `AmChartsService`](https://www.amcharts.com/kbase/migrating-amcharts-angular-plugin-1-2/).

We have also [updated our step-by-step instructions](https://github.com/amcharts/amcharts3-angular2#installation).

After changing your code, you can then access all of the chart methods.
