### ISSUE TITLE
amcharts 2.2.5 not compatible with angular 9.1.13 and 

### ISSUE THREAD

**Issue by kudeshiyah** [amcharts/amcharts3-angular2#137]
Getting Error:

> ERROR in node_modules/@amcharts/amcharts3-angular/es2015/index.d.ts:75:22 - error NG6002: Appears in the NgModule.imports of DashboardModule, but could not be resolved to an NgModule class.

> This likely means that the library (@amcharts/amcharts3-angular) which declares AmChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

package.json

> {
    "dependencies": {
      "@agm/core": "^1.1.0",
      "@amcharts/amcharts3-angular": "^2.2.5",
      "@amcharts/amcharts4": "^4.0.4",
      "@angular-devkit/build-angular": "~0.901.15",
      "@angular/animations": "^9.1.13",
      "@angular/cdk": "^8.2.3",
      "@angular/common": "9.1.13",
      "@angular/core": "^9.1.13",
      "@angular/elements": "^10.0.1",
      "@angular/fire": "^6.0.4",
      "@angular/flex-layout": "^9.0.0-beta.20",
      "@angular/forms": "9.1.13",
      "@angular/http": "7.2.15",
      "@angular/localize": "^9.1.13",
      "@angular/material": "^8.2.3",
      "@angular/platform-browser": "9.1.13",
      "@angular/platform-browser-dynamic": "9.1.13",
      "@angular/router": "9.1.13",
      "@angular/service-worker": "^9.1.13",
      "@formio/angular": "^5.2.0",
      "@kolkov/angular-editor": "^1.1.3",
      "@mobiscroll/angular-lite": "^4.10.6",
      "@ng-bootstrap/ng-bootstrap": "^5.1.4",
      "@ng-select/ng-select": "^3.7.3",
      "@ngx-pwa/local-storage": "^8.2.4",
      "@stripe/stripe-js": "^1.13.2",
      "@techiediaries/ngx-qrcode": "^9.1.0",
      "@types/core-js": "^2.5.0",
      "@types/googlemaps": "^3.30.10",
      "acorn": "^6.1.1",
      "amazon-quicksight-embedding-sdk": "^1.17.1",
      "angular-datetimerangepicker": "^2.4.2",
      "angular-file-uploader": "^7.0.3",
      "angular-gauge": "^3.1.3",
      "angular-resizable-element": "^1.2.0",
      "angular-tree-component": "^7.0.1",
      "angular2-counto": "^1.2.5",
      "angular2-datetimepicker": "^1.1.1",
      "angular2-moment": "^1.9.0",
      "angular2gridster": "^8.1.2",
      "angular4-tinymce-biznet": "^4.0.1",
      "aws-sdk": "^2.1002.0",
      "bootstrap": "^4.0.0-beta",
      "chart.js": "2.6.0",
      "ckeditor": "4.6.0",
      "classlist.js": "^1.1.20150312",
      "core-js": "^2.5.1",
      "d3": "^4.9.1",
      "datatables.net": "^1.10.16",
      "datatables.net-bs": "^1.10.16",
      "datatables.net-bs4": "^1.10.16",
      "datatables.net-buttons-bs4": "^1.5.1",
      "dayjs": "^1.10.4",
      "dragula": "3.7.2",
      "easy-pie-chart": "2.1.7",
      "firebase": "^8.0.0",
      "font-awesome": "4.7.0",
      "formiojs": "^4.13.10",
      "grpc": "^1.20.2",
      "hammerjs": "2.0.8",
      "hellojs": "1.15.1",
      "insert-text-at-cursor": "^0.3.0",
      "intl": "^1.2.4",
      "jquery": "^2.2.4",
      "jqvmap": "^1.5.1",
      "leaflet": "^1.0.2",
      "leaflet-map": "0.2.1",
      "linkifyjs": "^3.0.0-beta.3",
      "lodash": "^4.17.10",
      "mixpanel-browser": "^2.26.0",
      "mobiscroll-angular": "^4.0.0",
      "moment": "^2.24.0",
      "moment-timezone": "^0.5.21",
      "ng-sidebar": "^6.0.0",
      "ng2-ace-editor": "^0.3.4",
      "ng2-charts": "^2.4.3",
      "ng2-ckeditor": "1.1.9",
      "ng2-dnd": "^4.2.0",
      "ng2-drag-drop": "^2.5.0",
      "ng2-dragula": "^1.5.0",
      "ng2-file-upload": "1.2.1",
      "ng2-google-charts": "^3.5.0",
      "ng2-nouislider": "^1.7.13",
      "ng2-search-filter": "^0.5.1",
      "ng2-select": "^2.0.0",
      "ng2-translate": "5.0.0",
      "ng2-tree": "^2.0.0-rc.4",
      "ng2-validation": "4.2.0",
      "ng5-slider": "^1.1.13",
      "ng6-toastr-notifications": "^1.0.4",
      "ngrok": "^3.2.7",
      "ngx-audio-player": "^8.1.4",
      "ngx-chips": "^2.2.2",
      "ngx-color": "^3.0.3",
      "ngx-infinite-scroll": "^0.8.4",
      "ngx-mask": "^8.1.6",
      "ngx-mega-simple-drag-drop-list": "^1.0.8",
      "ngx-papaparse": "^2.1.4",
      "ngx-perfect-scrollbar": "^5.0.0",
      "ngx-toastr": "^8.10.2",
      "ngx-tour-ng-bootstrap": "^6.0.0",
      "ngx-ui-switch": "^8.1.0",
      "normalize.css": "^5.0.0",
      "nouislider": "^13.1.5",
      "nvd3": "^1.8.5",
      "papaparse": "^5.0.2",
      "perfect-scrollbar": "^1.2.0",
      "popper.js": "^1.12.5",
      "prettier": "^2.3.2",
      "ringcentral-web-phone": "^0.8.6",
      "rxjs": "6.5.3",
      "rxjs-compat": "^6.0.0-rc.0",
      "screenfull": "^3.2.2",
      "simple-line-icons": "^2.4.1",
      "skycons": "^1.0.0",
      "sortablejs": "^1.6.0",
      "summernote": "^0.8.4",
      "sweetalert2": "^7.18.0",
      "tether": "1.4.0",
      "textarea-helper": "^0.3.1",
      "ts-helpers": "^1.1.2",
      "tslib": "^1.10.0",
      "twilio-client": "^1.9.7",
      "web-animations-js": "^2.3.2",
      "widgster": "0.0.3",
      "zone.js": "~0.10.2"
    },
    "devDependencies": {
      "@angular/cli": "9.1.15",
      "@angular/compiler": "9.1.13",
      "@angular/compiler-cli": "9.1.13",
      "@datadog/browser-rum": "^2.6.0",
      "@nrwl/cli": "^12.5.0",
      "@nrwl/nx-cloud": "^12.2.7",
      "@nrwl/tao": "^12.5.0",
      "@nrwl/workspace": "^12.5.0",
      "@thisissoon/angular-inviewport": "^4.2.2",
      "@types/bootstrap": "^4.1.0",
      "@types/d3": "^4.12.0",
      "@types/jasmine": "2.6.3",
      "@types/jquery": "^3.3.32",
      "@types/lodash": "^4.14.116",
      "@types/moment": "^2.13.0",
      "@types/moment-timezone": "^0.5.6",
      "@types/node": "^12.11.1",
      "@types/nvd3": "^1.8.38",
      "@types/w3c-permissions": "^1.0.0",
      "angular-mentions": "^1.1.6",
      "codelyzer": "^5.1.2",
      "jasmine-core": "2.8.0",
      "jasmine-spec-reporter": "4.2.1",
      "karma": "1.7.1",
      "karma-chrome-launcher": "2.2.0",
      "karma-cli": "1.0.1",
      "karma-coverage-istanbul-reporter": "1.3.0",
      "karma-jasmine": "1.1.0",
      "karma-jasmine-html-reporter": "0.2.2",
      "ng-fullcalendar": "^1.7.1",
      "ng-select": "^1.0.2",
      "ng2-tooltip-directive": "^2.1.9",
      "ng2modules-easypiechart": "0.0.4",
      "ngx-color-picker": "^8.2.0",
      "ngx-print": "^1.2.0-beta.4",
      "ngx-quill": "^5.2.0",
      "prettier": "^2.3.2",
      "protractor": "5.2.0",
      "quill": "^1.3.7",
      "quill-mention": "^3.0.4",
      "ts-node": "^3.3.0",
      "tslint": "5.4.3",
      "typescript": "3.8.3",
      "webpack-bundle-analyzer": "^4.4.2",
      "xlsx": "^0.16.9"
    }
  }
  

Already closed issue - but its not working
[https://github.com/amcharts/amcharts3-angular2/issues/112](url)

**Comment by Pauan** [comment]
You need to upgrade to `@amcharts/amcharts3-angular` version `3.0.0`.
