### ISSUE TITLE
Include js build to the npm package

### ISSUE THREAD

**Issue by AlexanderLukin** [amcharts/amcharts3-angular2#14]
I can't import the directive from `node_modules` in my angular 2 project based on the [angular-seed](https://github.com/mgechev/angular-seed). This happens because the npm package of this directive doesn't provide its compiled version. It includes only TypeScript file with directive's source code. Can you please update the npm package to provide compiled js version, so I can import it with SystemJS?

**Comment by Pauan** [comment]
@AlexanderLukin Version `1.1.0` of `amcharts3-angular2` now includes the `.js` files as well as `.ts`

You can upgrade by deleting your `node_modules/amcharts3-angular2` folder and then running `npm install`
