### ISSUE TITLE
Amchart script fails on chart config gets updated

### ISSUE THREAD

**Issue by ArunYogi** [amcharts/amcharts3-angular2#17]
AmChart loads chart svg perfect on first data is passed to options. I added a **Refresh** button to provide "pull latest data on request" functionality. On click of refresh, latest data is pulled and new config object is constructed and set, then I got below error 
> TypeError: Cannot read property 'length' of null
>     at Zone._updateTaskCount (zone.js:224)
>     at Zone.cancelTask (zone.js:214)
>     at zone.js:1575
>     at clearTimeout (eval at createNamedFn (zone.js:1483), <anonymous>:3:39)
>     at Object.init (eval at webpackJsonp.214.module.exports (addScript.js:9), <anonymous>:2:21845)
>     at b.afterWrite (eval at webpackJsonp.214.module.exports (addScript.js:9), <anonymous>:111:145)
>     at b.write (eval at webpackJsonp.214.module.exports (addScript.js:9), <anonymous>:109:382)
>     at b.validateNow (eval at webpackJsonp.214.module.exports (addScript.js:9), <anonymous>:135:499)
>     at index.ts:268
>     at ZoneDelegate.invoke (zone.js:330)
>     at Zone.run (zone.js:126)
>     at NgZone.runOutsideAngular (ng_zone.js:164)
>     at AmChartsDirective.webpackJsonp.1815.AmChartsDirective.ngOnChanges (index.ts:263)
>     at Wrapper_AmChartsDirective.ngDoCheck (/AmChartsModule/AmChartsDirective/wrapper.ngfactory.js:41)
>     at CompiledTemplate.proxyViewClass.View_PieChartComponent0.detectChangesInternal (/DashboardModule/PieChartComponent/component.ngfactory.js:68)

App details:
```
Angular : 2.4.8
"zone.js": "0.7.7,
"typescript": "2.0.3",
"amcharts3": "github:amcharts/amcharts3",
"amcharts3-angular2": "github:amcharts/amcharts3-angular2",
```

Could you tell why this is happening?

**Comment by mbel24** [comment]
I have a very similar error with maps when I try to update data

**Comment by ArunYogi** [comment]
I investigates little bit, on this topic. I found that, issue is not with amcharts script file but with export plugin comes along with that, when disabled export function, refresh action worked as expected. Seems Amchart's export plugin script is not able to handle data change. I was able to reproduce the issue with sample project provided along with amcharts-angular. 
Any update on this ?

**Comment by mbel24** [comment]
Thank you for pointing that out.  Now works for me without the export enabled.  This issue will have to be addressed though.

**Comment by darlesson** [comment]
This error is happening in [zone.js](https://github.com/angular/zone.js). A similar issue was logged here: https://github.com/angular/zone.js/issues/643 and the fix was just merged into master: https://github.com/angular/zone.js/pull/642. This fix is not released yet. If you can wait, I recommend trying to copy https://github.com/angular/zone.js/blob/master/dist/zone.js to your project.

**Comment by Pauan** [comment]
This issue has been fixed. Please upgrade to the latest version of `zone.js`
