### ISSUE TITLE
NPM package with amcharts3-angular2

### ISSUE THREAD

**Issue by ryzy** [amcharts/amcharts3-angular2#18]
Hi,

Do you guys have any plans to push official AmCharts 3 into NPM registry?

For now the `package.json` name is specified as `amcharts3-angular2`, but `npm info amcharts3-angular2` says:

```
$ npm info amcharts3-angular2
...
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/amcharts3-angular2
npm ERR! 404 
npm ERR! 404  'amcharts3-angular2' is not in the npm registry.
```

**Comment by Pauan** [comment]
There is now an `@amcharts/amcharts3-angular` npm package.

**Comment by ryzy** [comment]
Well done @Pauan , thanks!
