### ISSUE TITLE
Chart options getting override automatically after rendering the chart

### ISSUE THREAD

**Issue by rahulscp** [amcharts/amcharts3-angular2#25]
hi all ,
i am using below code to create chart options dynamically and by using that i am rendering one chart

```
this.chartConfig = this.createChartConfig();
// this will return proper chart options.
        setTimeout(() => {
            this.chart = this.AmCharts.makeChart("configurationchart", this.chartConfig);
        }, 1)
```

once the chart rendered in the UI  chart options are getting overriding automatically with amchart options and turn out to be a complete different object with similar keys. since it have circular json structure i am not able to save the chart options though it changed.

any help highly appreciated..
thanks in advance.

**Comment by Pauan** [comment]
@rahulscp AmCharts modifies the chart configuration that you give to it.

If you do not want it to be modified, you will have to make a copy, like this:

```js
function copy(x) {
  return JSON.parse(JSON.stringify(x));
}

setTimeout(() => {
  this.chart = this.AmCharts.makeChart("configurationchart", copy(this.chartConfig));
}, 1)
```
