### ISSUE TITLE
not able to Install project

### ISSUE THREAD

**Issue by HimanshuMalviya** [amcharts/amcharts3-angular2#27]
Hello guys,

i am trying to install Amchart project but not able to install ... if you guys having basic steps which i  need to follow or what all the software i need to install excluding Node please help 

I am new to angular and my requirement is to develop a AmChart application 

1. i am using Angular CLI to create a basic Structure ... please help further ...

Thanks Regards

Himanshu

**Comment by ryzy** [comment]
Hi @HimanshuMalviya 

What issues do you experience with your installation process?

**Comment by Pauan** [comment]
@HimanshuMalviya We have step-by-step directions on [the README](https://github.com/amcharts/amcharts3-angular2#installation), and we also have [an `angular-cli` example](https://github.com/amcharts/amcharts3-angular2/tree/master/examples/angular-cli). You can find the code in the `src/app` folder.

**Comment by HimanshuMalviya** [comment]
This issue got resolved ... #there was a with my installed angular CLI which was required to be uninstall and cache clear .. #solved

**Comment by Pauan** [comment]
@HimanshuMalviya Okay, I'm glad you were able to fix the problem.
