### ISSUE TITLE
AmPieChart is not a constructor

### ISSUE THREAD

**Issue by jast1000** [amcharts/amcharts3-angular2#35]
Hello friends!

I found a error after try create pie chart:

### Typescript code
`this.amChart.makeChart("chartdiv", {
            "type": "pie",
            "theme": "light",
            "dataProvider": [{
                "title": "New",
                "value": 4852
            }, {
                "title": "Returning",
                "value": 9899
            }],
            "titleField": "title",
            "valueField": "value",
            "labelRadius": 5,
            "radius": "42%",
            "innerRadius": "60%",
            "labelText": "[[title]]",
            "export": {
                "enabled": true
            }
        });`

the creation work with serial chart, but pie chart not :(

**Comment by Pauan** [comment]
@jast1000 You have to include the `pie.js` file in order to use pie charts:

```html
<script src="https://www.amcharts.com/lib/3/pie.js"></script>
```

You have to place it underneath the `amcharts.js` file:

```html
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/pie.js"></script>
<script src="https://www.amcharts.com/lib/3/serial.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
```

**Comment by balrajhariharan** [comment]
If I want to implement pie chart with react, I have to add an extra dependency?

**Comment by Pauan** [comment]
@balrajhariharan Yes, you have to add the extra `<script src="https://www.amcharts.com/lib/3/pie.js"></script>` code in your HTML file.

**Comment by sujitnale123** [comment]
//.ts file 
export class AppComponent {
    title = 'app';
     private pieChart: AmChart;

ngOnInit() {
this.pieChart = this.AmCharts.makeChart("chartdiv2", this.makeOptions2());
}
makeOptions2() {
        return {
            "type": "pie",
            "theme": "light",
            "dataProvider": [{
                "country": "Lithuania",
                "value": 260
            }, {
                "country": "Ireland",
                "value": 201
            }, {
                "country": "Germany",
                "value": 65
            }, {
                "country": "Australia",
                "value": 39
            }, {
                "country": "UK",
                "value": 19
            }, {
                "country": "Latvia",
                "value": 10
            }],
            "valueField": "value",
            "titleField": "country",
            "outlineAlpha": 0.4,
            "depth3D": 15,
            "balloonText": "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>",
            "angle": 30,
            "export": {
                "enabled": true
            }
        }
    }
}

//.Html file 

<app-root>
        <script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
        <script src="https://www.amcharts.com/lib/3/pie.js"></script>
        <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
        <script src="https://www.amcharts.com/lib/3/serial.js"></script>
        <script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
    </app-root>

//.css file

#chartdiv2{
    width: 100%;
    height:500px;
  }

all code is placed properly.. still pie chart is not getting displayed

**Comment by nisriinaaulfah** [comment]
hi @sujitnale123 , did you find out how to fix your problem? because now I'm facing that problem too.

**Comment by moghthalkushal** [comment]
Ensure it is in your index.html

**Comment by sumitramteke** [comment]
Make sure `serial.js` is above `pie.js`
