### ISSUE TITLE
Exporting problem

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts3-angular2#37]
Hey I have use amcharts3-angular2 directive for displaying a simple bar charts.
When I am define property export:true, I get the following errors:
[https://ibb.co/g8wmwQ](url)

What can I do to handle this errors properly, why it doesn't find the right files?
This is the code in angular 2 :
`import { Component, OnInit, OnDestroy } from '@angular/core';
import { AmChartsService } from "amcharts3-angular2";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit, OnDestroy {
  title = 'app works!';
  private chart: any;

  constructor(private AmCharts: AmChartsService) { }

  ngOnInit() {
    this.chart = this.AmCharts.makeChart("chartdiv", {
      "type": "serial",
      "theme": "light",
      "marginRight": 70,
      "dataProvider": [{
        "country": "USA",
        "visits": 3025,
        "color": "#FF0F00"
      }, {
        "country": "China",
        "visits": 1882,
        "color": "#FF6600"
      }, {
        "country": "Japan",
        "visits": 1809,
        "color": "#FF9E01"
      }, {
        "country": "Germany",
        "visits": 1322,
        "color": "#FCD202"
      }, {
        "country": "UK",
        "visits": 1122,
        "color": "#F8FF01"
      }, {
        "country": "France",
        "visits": 1114,
        "color": "#B0DE09"
      }, {
        "country": "India",
        "visits": 984,
        "color": "#04D215"
      }, {
        "country": "Spain",
        "visits": 711,
        "color": "#0D8ECF"
      }, {
        "country": "Netherlands",
        "visits": 665,
        "color": "#0D52D1"
      }, {
        "country": "Russia",
        "visits": 580,
        "color": "#2A0CD0"
      }, {
        "country": "South Korea",
        "visits": 443,
        "color": "#8A0CCF"
      }, {
        "country": "Canada",
        "visits": 441,
        "color": "#CD0D74"
      }],
      "valueAxes": [{
        "axisAlpha": 0,
        "position": "left",
        "title": "Visitors from country"
      }],
      "startDuration": 1,
      "graphs": [{
        "balloonText": "<b>[[category]]: [[value]]</b>",
        "fillColorsField": "color",
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "type": "column",
        "valueField": "visits"
      }],
      "chartCursor": {
        "categoryBalloonEnabled": false,
        "cursorAlpha": 0,
        "zoomable": false
      },
      "categoryField": "country",
      "categoryAxis": {
        "gridPosition": "start",
        "labelRotation": 45
      },
      "export": {
        "enabled": true
      }

    });
    this.chart.path = "/node_modules/amcharts3/amcharts/";
  }

  ngOnDestroy() {
    this.AmCharts.destroyChart(this.chart);
  }
}
`

**Comment by jsJunky** [comment]
I can't see your errors but make sure you add AmChartsModule to your app.module.ts imports.

Also I added the following in app.module.ts above the NgModule declaration because it appears the service requires AmCharts to be on the window object.

```ts
import 'amcharts3/amcharts/amcharts';
import 'amcharts3/amcharts/serial';
import 'amcharts3/amcharts/them';
```

**Comment by Pauan** [comment]
@BrkCoder AmCharts 3 doesn't work correctly with npm, so make sure that you are using `<script>` tags, like this:

```
<link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/serial.js"></script>
<script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
```

**Comment by jsJunky** [comment]
Don't need to add the script tags. Just import them as stated above. @Pauan is incorrect here.

**Comment by Pauan** [comment]
@jsJunky That is incorrect. They are already using `import` to load `amcharts3`

The export plugin requires you to use `<script>` tags because it dynamically loads its dependencies based upon its base URL. If you don't use `<script>` tags, you [will get errors](https://ibb.co/g8wmwQ).

You can go ahead and try it yourself. Just try using the `export` plugin with `import`:

```
import 'amcharts3/amcharts/plugins/export/export';

// Chart configuration
this.AmCharts.makeChart("chartdiv", {
  "export": {
    "enabled": true
  }
});
```

[There are multiple good reasons](https://github.com/amcharts/amcharts3-react/issues/41#issuecomment-293155215) why we recommend our users to use `<script>` tags rather than importing.

**Comment by jsJunky** [comment]
I think the problems being worked around by using scrip tags have alternative solutions that would allow for a more friendly TS env. That said I don't know the work required and the team size maintaining so I won't make assumptions here.

Look like importing will be an issue as there are requires throughout that are looking in the current directory for the files rather than up one directory to match the export/libs directory structure. Will wait to use / discuss blocking the export functionality temporarily.

Thanks for the explanation @Pauan

**Comment by moghthalkushal** [comment]
@Pauan , do you have a working example of export all charts to pdf using angular6

**Comment by Pauan** [comment]
@moghthalkushal Here is a Codepen which shows how to export multiple charts with `amcharts3`:

https://codepen.io/team/amcharts/pen/920ad87624f04d37473fd9c10f5155ef

In order to translate it into `amcharts3-angular`, you just need to make `exportCharts` a method on the class, and replace `AmCharts` with `this.AmCharts`, like this:

```html
<input type="button" value="Export charts to PDF" (click)="exportCharts()" />
<div id="chart1" class="chartdiv"></div>
<div id="chart2" class="chartdiv"></div>
<div id="chart3" class="chartdiv"></div>
```

```ts
export class AppComponent {
  constructor(private AmCharts: AmChartsService) {}

  ngAfterViewInit() {
    this.AmCharts.makeChart( "chart1", {
      "type": "serial",
      "theme": "light",
      "autoMargins": false,
      "marginLeft": 50,
      "marginRight": 8,
      "marginTop": 30,
      "marginBottom": 26,
      "dataProvider": [ {
        "country": "USA",
        "visits": 2025
      }, {
        "country": "China",
        "visits": 1882
      }, {
        "country": "Japan",
        "visits": 1809
      }, {
        "country": "Germany",
        "visits": 1322
      }, {
        "country": "UK",
        "visits": 1122
      }, {
        "country": "France",
        "visits": 1114
      }, {
        "country": "India",
        "visits": 984
      }, {
        "country": "Spain",
        "visits": 711
      } ],
      "valueAxes": [ {
        "gridColor": "#FFFFFF",
        "gridAlpha": 0.2,
        "dashLength": 0
      } ],
      "startDuration": 1,
      "graphs": [ {
        "balloonText": "[[category]]: <b>[[value]]</b>",
        "fillAlphas": 0.8,
        "lineAlpha": 0.2,
        "type": "column",
        "valueField": "visits"
      } ],
      "chartCursor": {
        "categoryBalloonEnabled": false,
        "cursorAlpha": 0,
        "zoomable": false
      },
      "categoryField": "country",
      "categoryAxis": {
        "gridPosition": "start",
        "gridAlpha": 0,
        "tickPosition": "start",
        "tickLength": 20
      },
      "export": {
        "enabled": true,
        "menu": []
      }

    } );

    this.AmCharts.makeChart( "chart2", {
      "type": "serial",
      "addClassNames": true,
      "theme": "light",
      "autoMargins": false,
      "marginLeft": 50,
      "marginRight": 8,
      "marginTop": 30,
      "marginBottom": 26,
      "balloon": {
        "adjustBorderColor": false,
        "horizontalPadding": 10,
        "verticalPadding": 8,
        "color": "#ffffff"
      },

      "dataProvider": [ {
        "year": 2009,
        "income": 23.5,
        "expenses": 21.1
      }, {
        "year": 2010,
        "income": 26.2,
        "expenses": 30.5
      }, {
        "year": 2011,
        "income": 30.1,
        "expenses": 34.9
      }, {
        "year": 2012,
        "income": 29.5,
        "expenses": 31.1
      }, {
        "year": 2013,
        "income": 30.6,
        "expenses": 28.2,
      }, {
        "year": 2014,
        "income": 34.1,
        "expenses": 32.9,
        "dashLengthColumn": 5,
        "alpha": 0.2,
        "additional": "(projection)"
      } ],
      "valueAxes": [ {
        "gridColor": "#FFFFFF",
        "gridAlpha": 0.2,
        "dashLength": 0
      } ],
      "startDuration": 1,
      "graphs": [ {
        "alphaField": "alpha",
        "balloonText": "<span style='font-size:12px;'>[[title]] in [[category]]:<br><span style='font-size:20px;'>[[value]]</span> [[additional]]</span>",
        "fillAlphas": 1,
        "title": "Income",
        "type": "column",
        "valueField": "income",
        "dashLengthField": "dashLengthColumn"
      }, {
        "id": "graph2",
        "balloonText": "<span style='font-size:12px;'>[[title]] in [[category]]:<br><span style='font-size:20px;'>[[value]]</span> [[additional]]</span>",
        "bullet": "round",
        "lineThickness": 3,
        "bulletSize": 7,
        "bulletBorderAlpha": 1,
        "bulletColor": "#FFFFFF",
        "useLineColorForBulletBorder": true,
        "bulletBorderThickness": 3,
        "fillAlphas": 0,
        "lineAlpha": 1,
        "title": "Expenses",
        "valueField": "expenses"
      } ],
      "categoryField": "year",
      "categoryAxis": {
        "gridPosition": "start",
        "gridAlpha": 0,
        "tickPosition": "start",
        "tickLength": 20
      },
      "export": {
        "enabled": true,
        "menu": []
      }
    } );

    this.AmCharts.makeChart( "chart3", {
      "type": "serial",
      "theme": "light",
      "autoMargins": false,
      "marginLeft": 50,
      "marginRight": 8,
      "marginTop": 30,
      "marginBottom": 26,
      "dataProvider": [ {
        "date": "2012-03-01",
        "price": 20
      }, {
        "date": "2012-03-02",
        "price": 75
      }, {
        "date": "2012-03-03",
        "price": 15
      }, {
        "date": "2012-03-04",
        "price": 75
      }, {
        "date": "2012-03-05",
        "price": 158
      }, {
        "date": "2012-03-06",
        "price": 57
      }, {
        "date": "2012-03-07",
        "price": 107
      }, {
        "date": "2012-03-08",
        "price": 89
      }, {
        "date": "2012-03-09",
        "price": 75
      }, {
        "date": "2012-03-10",
        "price": 132
      }, {
        "date": "2012-03-11",
        "price": 158
      }, {
        "date": "2012-03-12",
        "price": 56
      }, {
        "date": "2012-03-13",
        "price": 169
      }, {
        "date": "2012-03-14",
        "price": 24
      }, {
        "date": "2012-03-15",
        "price": 147
      } ],
      "valueAxes": [ {
        "logarithmic": true,
        "dashLength": 1,
        "guides": [ {
          "dashLength": 6,
          "inside": true,
          "label": "average",
          "lineAlpha": 1,
          "value": 90.4
        } ],
        "position": "left"
      } ],
      "graphs": [ {
        "bullet": "round",
        "id": "g1",
        "bulletBorderAlpha": 1,
        "bulletColor": "#FFFFFF",
        "bulletSize": 7,
        "lineThickness": 2,
        "title": "Price",
        "type": "smoothedLine",
        "useLineColorForBulletBorder": true,
        "valueField": "price"
      } ],
      "chartCursor": {
        "valueLineEnabled": true,
        "valueLineBalloonEnabled": true,
        "valueLineAlpha": 0.5,
        "fullWidth": true,
        "cursorAlpha": 0.05
      },
      "dataDateFormat": "YYYY-MM-DD",
      "categoryField": "date",
      "categoryAxis": {
        "parseDates": true,
        "gridPosition": "start",
        "gridAlpha": 0,
        "tickPosition": "start",
        "tickLength": 20
      },
      "export": {
        "enabled": true,
        "menu": []
      }
    } );
  }

  exportCharts() {
    // iterate through all of the charts and prepare their images for export
    var images = [];
    var pending = this.AmCharts.charts.length;
    for ( var i = 0; i < this.AmCharts.charts.length; i++ ) {
      var chart = this.AmCharts.charts[ i ];
      chart.export.capture( {}, function() {
        this.toJPG( {
          multiplier: 2
        }, function( data ) {
          images.push( {
            "image": data,
            "fit": [ 523.28, 769.89 ]
          } );
          pending--;
          if ( pending === 0 ) {
            // all done - construct PDF
            chart.export.toPDF( {
              content: images
            }, function( data ) {
              this.download( data, "application/pdf", "amCharts.pdf" );
            } );
          }
        } );
      } );
    }
  }
}
```

**Comment by moghthalkushal** [comment]
@Pauan  Thank you for your reply , i am not able to get AmExport  , it says AmExport is not a constructor. 

Uncaught TypeError: chart.export.capture is not a function
    at exportCharts (<anonymous>:7:20)
    at <anonymous>:1:1

https://github.com/amcharts/amcharts3-angular2/issues/35

Your solution works fine in plain HTML

<script type="text/javascript" src="http://www.amcharts.com/lib/3/amcharts.js"></script>
<script type="text/javascript" src="http://www.amcharts.com/lib/3/exporting/amexport_combined.js"></script>
<script type="text/javascript" src="http://www.amcharts.com/lib/3/serial.js"></script>
<script type="text/javascript" src="http://www.amcharts.com/lib/3/themes/none.js"></script>
<style>
    #chartdiv {
        width: 100%;
        height: 500px;
/
    }
</style>

<button id="export">Export</button>


<div id="chartdiv"></div>


<script type="text/javascript">

    var chart;

    var chartData = [{
        "country": "USA",
        "visits": 4025,
        "color": "#FF0F00"
    }, {
        "country": "China",
        "visits": 1882,
        "color": "#FF6600"
    }, {
        "country": "Japan",
        "visits": 1809,
        "color": "#FF9E01"
    }, {
        "country": "Germany",
        "visits": 1322,
        "color": "#FCD202"
    }, {
        "country": "UK",
        "visits": 1122,
        "color": "#F8FF01"
    }, {
        "country": "France",
        "visits": 1114,
        "color": "#B0DE09"
    }, {
        "country": "India",
        "visits": 984,
        "color": "#04D215"
    }, {
        "country": "Spain",
        "visits": 711,
        "color": "#0D8ECF"
    }, {
        "country": "Netherlands",
        "visits": 665,
        "color": "#0D52D1"
    }, {
        "country": "Russia",
        "visits": 580,
        "color": "#2A0CD0"
    }, {
        "country": "South Korea",
        "visits": 443,
        "color": "#8A0CCF"
    }, {
        "country": "Canada",
        "visits": 441,
        "color": "#CD0D74"
    }, {
        "country": "Brazil",
        "visits": 395,
        "color": "#754DEB"
    }, {
        "country": "Italy",
        "visits": 386,
        "color": "#DDDDDD"
    }, {
        "country": "Australia",
        "visits": 384,
        "color": "#999999"
    }, {
        "country": "Taiwan",
        "visits": 338,
        "color": "#333333"
    }, {
        "country": "Poland",
        "visits": 328,
        "color": "#000000"
    }];


    var chart = AmCharts.makeChart("chartdiv", {
        "theme": "none",
        type: "serial",
        dataProvider: chartData,
        categoryField: "country",
        depth3D: 20,
        angle: 30,

        categoryAxis: {
            labelRotation: 90,
            gridPosition: "start"
        },

        valueAxes: [{
            title: "Visitors"
        }],

        graphs: [{

            valueField: "visits",
            colorField: "color",
            type: "column",
            lineAlpha: 0.1,
            fillAlphas: 1
        }],

        chartCursor: {
            cursorAlpha: 0,
            zoomable: false,
            categoryBalloonEnabled: false
        }
    });

    var btn = document.getElementById('export');
    btn.onclick = function () {
        var tmp = new AmCharts.AmExport(chart);
        tmp.init();
        tmp.output({
            output: 'datastring',
            format: 'png'
        }, function (blob) {
            var image = new Image();
            image.src = blob;



            var a = document.createElement("a");
            a.download = 'download' + ".png";
            a.href = blob;
            a.click();

            document.body.appendChild(image);
        });
    }



</script>


But not in Angular , can suggest the right libraries to be imported for the same.

**Comment by Pauan** [comment]
@moghthalkushal Your HTML code needs to look like this:

```html
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/serial.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/none.js"></script>
<script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
<link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
```

Make sure that the `<script>` and `<link>` tags are in your `index.html`, not in your template's HTML.

**Comment by moghthalkushal** [comment]
Thank you , yeah this works, I wanted to check with you is there any option to use them in import statement of angular  ?

**Comment by Pauan** [comment]
@moghthalkushal No, unfortunately it is necessary to use `<script>` tags to load AmCharts V3, because V3 is very old, so it wasn't designed for import statements.

However, we [currently have a beta for V4](https://www.amcharts.com/docs/v4/), which has excellent support for npm/Webpack/Angular, so you don't need to use `<script>` tags anymore.

**Comment by moghthalkushal** [comment]
Awesome , thanks for the update .  We really appreciate your help.

**Comment by moghthalkushal** [comment]
This works in plain angular app , but not in my angular ,
analysis-header.component.html:23 ERROR TypeError: chart.export.capture is not a function
Despite the fact i have all the above libraries mentioned in my index.html file.

**Comment by dmitrystril** [comment]
This also works in codepen like this one: [https://codepen.io/team/amcharts/pen/e487525e17e43a9d2de41d71f525b721](url)
But doesn't work in my React app. Also says: 

> chart.export.capture is not a function
