### ISSUE TITLE
How to call var data = AmCharts.parseCSV( response, {"useColumnNames": true 		  } );

### ISSUE THREAD

**Issue by gambulator** [amcharts/amcharts3-angular2#38]
I can't seem to call parseCSV and the code doesn't seem to have it. How do I call this function ?

**Comment by Pauan** [comment]
Hi @gambulator,

You have to load the [dataloader](https://github.com/amcharts/dataloader) plugin in order to use the `AmCharts.parseCSV` function:

```html
<script src="https://www.amcharts.com/lib/3/plugins/dataloader/dataloader.min.js"></script>
```
