### ISSUE TITLE
Cannot find module "amcharts3-angular2/amcharts.directive" on Ionic 2 project

### ISSUE THREAD

**Issue by MehdiAR** [amcharts/amcharts3-angular2#4]
I followed the steps, but while bundling, I got that Error : Cannot find module "amcharts3-angular2/amcharts.directive"

`import { AmChartsDirective } from "amcharts3-angular2/amcharts.directive";

@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage,
    AmChartsDirective
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: []
})
export class AppModule {}
`

Any ideas please

**Comment by delian7** [comment]
@MehdiAR I'm having the same issue. Wondering what steps you tried? I'll keep trying and update if i get any progress.

**Comment by MehdiAR** [comment]
@delian7 I still have the same error.

**Comment by Pauan** [comment]
@MehdiAR Does it work with a regular Angular 2 app?

Ionic 2 is **very** new, so it may be an incompatibility in their system.

----

Try using this instead:

```
import { AmChartsDirective } from "amcharts3-angular2/amcharts.directive.ts";
```

(Notice the `.ts` extension at the end)

**Comment by QuocMinhTran** [comment]
add this row to your systemjs.config.js in curly bracket of the map:
`'amcharts3-angular2/amcharts.directive': 'npm:amcharts3-angular2/amcharts.directive.js'`

**Comment by delian7** [comment]
@QuocMinhTran there is no folder called systemjs.config.js in ionic2. @Pauan when I copy the amcharts.directive.ts to the components folder and call `import { AmChartsDirective } from "./amcharts.directive";` it works so I don't think it's a ionic2 thing but I am kinda novice at angular/ionic/ts. 

I tried to call `import { AmChartsDirective } from "../../node_modules/amcharts3-angular2/amcharts.directive";` but it doesn't work

**Comment by Pauan** [comment]
@MehdiAR @delian7 I think I figured out the problem. I'm pretty sure Ionic requires any libraries to use `.js` files, not `.ts`

Version `1.1.0` of `amcharts3-angular2` now includes the `.js` files as well as `.ts`

You can upgrade by deleting your `node_modules/amcharts3-angular2` folder and then running `npm install`

**Comment by delian7** [comment]
@Pauan still not working for me. I tried to follow the updated readme by `import { AmChartsModule } from "amcharts3-angular2";` and I get a console error in my browser: 

```
Uncaught Error: Cannot find module "."
    at webpackMissingModule (main.js:113080)
    at main.js:113080
    at Object.<anonymous> (main.js:113085)
    at __webpack_require__ (bootstrap eca0fb0…:19)
    at Object.<anonymous> (main.js:101815)
    at __webpack_require__ (bootstrap eca0fb0…:19)
    at Object.<anonymous> (module.js:20)
    at __webpack_require__ (bootstrap eca0fb0…:19)
    at bootstrap eca0fb0…:65
    at bootstrap eca0fb0…:65
```

It might be worth noting that when I did an `npm install` I got:
`amcharts3-angular2@1.1.0 requires a peer of @angular/core@^2.4.7 but none was installed.`

and to my knowledge `ionic 2.0.1` needs `@angular/core@^2.2.1`

**Comment by frndxyz** [comment]
i am also getting same error in ionic 2 angular 2
