### ISSUE TITLE
index.ts in the published package is causing trouble

### ISSUE THREAD

**Issue by racerhere** [amcharts/amcharts3-angular2#41]
There is a index.ts in the `proj_root/node_modules/@amcharts/amcharts3-angular` folder when you add the dependency using `npm install @amcharts/amcharts3-angular --save`.

It does not follow the official [Angular Package Format](https://goo.gl/AMOU5G) because you do not need the index.ts file, since it is already compiled to JavaScript

The bigger problem is when you try to compile a `NgModule` that imports the `AmChartsModule` (`import { AmChartsModule } from '@amcharts/amcharts3-angular';`) into a reusable module. The ngc or tsc compilers prefer the `index.ts` over the `index.d.ts` when both are present at the time of module resolution. Removing the `index.ts` from the published package will prevent it.

**Comment by Pauan** [comment]
@racerhere That's very odd.

The `index.js` and `index.d.ts` files aren't in the root folder, they're in the `umd` folder. And the [main](https://github.com/amcharts/amcharts3-angular2/blob/a898132287b84b772fc0b224d60402ce328c6e92/package.json#L5) property in `package.json` correctly points to the `umd` folder.

So there shouldn't be any conflict with `index.ts`

What is your `moduleResolution` set to in the `tsconfig.json` file?

**Comment by racerhere** [comment]
@Pauan, please clone this [repository](https://github.com/racerhere/ng-am-charts) and try running the compile script
> `yarn run compile`

**Comment by Pauan** [comment]
@racerhere Thanks! I was able to reproduce the issue, and it has been fixed.

Please upgrade to version 1.2.1
