### ISSUE TITLE
AmCharts is not defined

### ISSUE THREAD

**Issue by faang94** [amcharts/amcharts3-angular2#54]
Solution: 
you have to import (for a serial chart with light theme) these files into _index.html_ ! Not into _example.component.html_ file!
```
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/serial.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
```

**Comment by Pauan** [comment]
Thanks, I have updated the README to be more clear.

**Comment by aminebousselmi** [comment]
Hi, i'am using Angular 5 with amcharts3 but i have an error : 

```
core.js:1350 ERROR ReferenceError: AmCharts is not defined
    at eval (index.js:636)
    at ZoneDelegate.invoke (zone.js:388)
    at Zone.run (zone.js:138)
    at NgZone.runOutsideAngular (core.js:4578)
    at AmChartsService.makeChart (index.js:636)
    at DashboardComponent.CreateChartChange (dashboard.component.ts:68)
    at SafeSubscriber.eval [as _next] (dashboard.component.ts:53)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:240)
    at SafeSubscriber.next (Subscriber.js:187)
    at Subscriber._next (Subscriber.js:128)

I import amchart in my component.ts using : 
`import { AmChartsService, AmChart } from "@amcharts/amcharts3-angular";


this is my creation chart : 
```
 CreateChartChange(){
    this.chartChange =  this.AmCharts.makeChart( "chartdiv", {
      "type": "gauge",
      "theme": "light",
      "axes": [ {
        "axisThickness": 1,
        "axisAlpha": 0.2,
        "tickAlpha": 0.2,
        "valueInterval": 20,
        "bands": [ {
          "color": "#84b761",
          "endValue": 90,
          "startValue": 0
        }, {
          "color": "#fdd400",
          "endValue": 130,
          "startValue": 90
        }, {
          "color": "#cc4748",
          "endValue": 220,
          "innerRadius": "95%",
          "startValue": 130
        } ],
        "bottomText": "0 km/h",
        "bottomTextYOffset": -20,
        "endValue": 220
      } ],
      "arrows": [ {} ],
      "export": {
        "enabled": true
      }
    } );
  }
```

And this is My Component.html

```
<div class="row">
        <div id="chartdiv"></div>
 </div>
```

**Comment by nicats** [comment]
@aminebousselmi you should import amchart scripts in index.html like 
  ```
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
            <script src="https://www.amcharts.com/lib/3/serial.js"></script>
            <script src="https://www.amcharts.com/lib/3/pie.js"></script>
            <script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
```
