### ISSUE TITLE
Switch to ngAfterViewInit

### ISSUE THREAD

**Issue by ryzy** [amcharts/amcharts3-angular2#55]
Hi @Pauan 

I see you switched from `ngOnInit` to `ngAfterViewInit` (as per commit https://github.com/amcharts/amcharts3-angular2/commit/93b781ed3e12c8206248af3ae724f6317c60a5f1 ). Can you elaborate why such change?

I'm having some issues with AmCharts `listeners` and I see switching to `ngAfterViewInit` seems to resolve the issue. But it's perhaps not ideal, because AmChart is not really rendered as a view child and theoretically should work correctly with `ngOnInit`. 

I wonder what were your reasons?

Many thanks!
M.

**Comment by Pauan** [comment]
@ryzy Angular calls `ngOnInit` immediately, before any of the child components have been initialized.

That also applies to HTML elements like `<div>`. You can verify that with this code:

```
@Component({
  template: `<div id="{{id}}"></div>`
})
export class AppComponent {
  id = "chartdiv";

  ngOnInit() {
    console.log(document.getElementById("chartdiv"));
  }

  ngAfterViewInit() {
    console.log(document.getElementById("chartdiv"));
  }
}
```

You will see that within `ngOnInit`, the `<div>` doesn't exist, but it does exist in `ngAfterViewInit`

When you call `this.AmCharts.makeChart("chartdiv", ...)` it will look for a `<div>` which has an id of `chartdiv`, therefore the `<div>` must exist, therefore it is necessary to use `ngAfterViewInit`
