### ISSUE TITLE
Support for angular5

### ISSUE THREAD

**Issue by tigredonorte** [amcharts/amcharts3-angular2#59]
angular v5.0.1 is available, and i can't upgrade to newer version because amcharts dependencie blocks update...

**Comment by Pauan** [comment]
@tigredonorte You are right, we will get this fixed ASAP. Thanks for letting us know!

**Comment by Pauan** [comment]
@tigredonorte We have upgraded `@amcharts/amcharts3-angular` to use Angular 5.

Please upgrade to version `2.0.3` of `@amcharts/amcharts3-angular`

**Comment by tigredonorte** [comment]
thanks!!

**Comment by lbevanda** [comment]
Everything works flawless with Angular ^5, Angular CLI 1.5.0, Node 8.9.0, AmCharts ^2.0.3, LInux x64. Thanks for quick support for Angular 5!
