### ISSUE TITLE
Metadata version mismatch for module Amcharts..

### ISSUE THREAD

**Issue by nirnaykulshreshtha** [amcharts/amcharts3-angular2#60]
Hello, @Pauan  
Trying to integrate amcharts in my angular 4 application but is throwing the following error 
![untitled](https://user-images.githubusercontent.com/11512781/33168592-7dc87190-d067-11e7-84e8-8ed6b975c375.png)

**Comment by xino1010** [comment]
+1

**Comment by Pauan** [comment]
Because you are using Angular 4, you must use version `1.5.0` of `@amcharts/amcharts3-angular`. This is necessary because Angular 5 has breaking changes.

We recommend upgrading to Angular 5, so that way you can use version `2.0.3` of `@amcharts/amcharts3-angular`
