### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by nisriinaaulfah** [amcharts/amcharts3-angular2#62]
Hi all, I use amcharts for my angular2 but I got this error: 

ERROR in Error: Metadata version mismatch for module /home/badix3/ng2-admin/node_modules/@amcharts/amcharts3-angular/es2015/index.d.ts, found version 4, expected 3, resolving symbol TrxModule in /home/badix3/ng2-admin/src/app/pages/trx/trx.module.ts, resolving symbol TrxModule in /home/badix3/ng2-admin/src/app/pages/trx/trx.module.ts

can you tell me what can I do? Thank you in advance

**Comment by Pauan** [comment]
Because you are using Angular 2, you must use version `1.5.0` of `@amcharts/amcharts3-angular`. This is necessary because Angular 5 has breaking changes.

We recommend upgrading to Angular 5, so that way you can use version `2.0.3` of `@amcharts/amcharts3-angular`
