### ISSUE TITLE
Question Regarding other AmChartsService methods

### ISSUE THREAD

**Issue by justinbleach** [amcharts/amcharts3-angular2#63]
Hello!

We're moving to Angular 4 and your library looks awesome for getting AmCharts into our project.

We are calling different methods though. For example:
AmCharts.StockPanel()
AmCharts.ValueAxis()
AmCharts.StockGraph()

How would I call these through your library?

**Comment by Pauan** [comment]
@justinbleach This plugin supports all chart types, however you must use our JSON configuration:

```typescript
this.chart = this.AmCharts.makeChart("chartdiv", {
  "type": "stock",
  "panels": [{
    "title": "Value",
    "stockGraphs": [{
      "valueField": "value"
    }]
  }],
  "dataSets": [{
    "color": "#b0de09",
    "fieldMappings": [{
      "fromField": "value",
      "toField": "value"
    }, {
      "fromField": "volume",
      "toField": "volume"
    }],
    "dataProvider": this.chartData,
    "categoryField": "date"
  }],
  ...
});
```

You also need to add the appropriate `<script>` tags in your `index.html` file:

```html
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/amstock.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
```

**Comment by justinbleach** [comment]
@Pauan so it looks like when I would normally called `var panel = new AmCharts.StockPanel()` that instead the object I create afterwards that I would call `panel.id=` or `panel.title` is actually is the object you have instead the `panels` attribute array in your example?

And so then the same for AmChart.StockGraph, those objects go in the `stockgraphs` array attribute?

Where would the ValueAxis objects go? 

Thanks for your time!

**Comment by Pauan** [comment]
@justinbleach Yes, except it's not `stockgraphs`, instead you must use the [`stockGraphs`](https://docs.amcharts.com/3/javascriptstockchart/StockPanel#stockGraphs) array inside of the [`panels`](https://docs.amcharts.com/3/javascriptstockchart/AmStockChart#panels) array:

```typescript
this.chart = this.AmCharts.makeChart("chartdiv", {
  "type": "stock",
  "panels": [{
    "stockGraphs": [{
      "valueField": "value1"
    }],
  }],
  ...
});
```

Also, you don't need to call `new AmCharts.StockPanel()` or `new AmCharts.StockGraph()` anymore, you can just use regular JSON objects (as in my examples).

You can see [our documentation](https://docs.amcharts.com/3/javascriptstockchart/AmStockChart) for the full list of all the object properties you can use.

And you can see more information about our JSON configuration [here](https://www.amcharts.com/kbase/creating-charts-using-json/).

For `ValueAxis` objects you would use the [`valueAxes`](https://docs.amcharts.com/3/javascriptstockchart/StockPanel#valueAxes) array inside of the [`panels`](https://docs.amcharts.com/3/javascriptstockchart/AmStockChart#panels) array, like this:

```typescript
this.chart = this.AmCharts.makeChart("chartdiv", {
  "type": "stock",
  "panels": [{
    "valueAxes": [{
      "title": "Axis title"
    }],
  }],
  ...
});
```

You can also use [`valueAxesSettings`](https://docs.amcharts.com/3/javascriptstockchart/AmStockChart#valueAxesSettings) to set some properties for all of the value axes:

```typescript
this.chart = this.AmCharts.makeChart("chartdiv", {
  "type": "stock",
  "valueAxesSettings": {
    "inside": false
  },
  ...
});
```
