### ISSUE TITLE
Stock chart doesn't work.

### ISSUE THREAD

**Issue by justinbleach** [amcharts/amcharts3-angular2#65]
When I use a serial type chart I can see the chart but if I switch the type to stock it does not and I have imported the stock scripts.

My angular-cli:
`"scripts": [
        "../node_modules/amstock3/amcharts/amcharts.js",
        "../node_modules/amstock3/amcharts/amstock.js",
        "../node_modules/amstock3/amcharts/serial.js",
        "../node_modules/amcharts3/amcharts/xy.js",
        "../node_modules/amcharts3/amcharts/radar.js",
        "../node_modules/amcharts3/amcharts/funnel.js",
        "../node_modules/amcharts3/amcharts/gantt.js",
        "../node_modules/amcharts3/amcharts/gauge.js",
        "../node_modules/amcharts3/amcharts/pie.js",     
        "../node_modules/amstock3/amcharts/themes/light.js",
        "../node_modules/amcharts3/amcharts/plugins/dataloader/dataloader.min.js"`

I'm using a basic chart, straight from the AmCharts website

`ngAfterViewInit() {
        
        this.chart = this.AmCharts.makeChart("chartDiv",{
            "type": "serial",
            "categoryField": "category",
            "categoryAxis": {
              "gridPosition": "start"
            },
            "graphs": [
              {
                "title": "Graph title",
                "valueField": "column-1"
              }
            ],
            "valueAxes": [
              {
                "title": "Axis title"
              }
            ],
            "legend": {
              "useGraphSettings": true
            },
            "titles": [
              {
                "size": 15,
                "text": "Chart Title"
              }
            ],
            "dataProvider": [
              {
                "category": "category 1",
                "column-1": 8
              },
              {
                "category": "category 2",
                "column-1": 10
              },
            ]
          });`

If I change this chart's type to stock I don't even see the "made by...." watermark.

**Comment by Pauan** [comment]
@justinbleach Because `stock` charts have extra features that `serial` charts do not have, the configuration for `stock` charts is different. Try this instead:

```typescript
this.chart = this.AmCharts.makeChart("chartDiv",{
  "type": "stock",
  "dataSets": [
    {
      "fieldMappings": [
      {
          "fromField": "column-1",
          "toField": "column-1"
        }
      ],
      "dataProvider": [
        {
          "category": "category 1",
          "column-1": 8
        },
        {
          "category": "category 2",
          "column-1": 10
        },
      ]
    }
  ],
  "panels": [
    {
      "categoryField": "category",
      "categoryAxis": {
        "gridPosition": "start"
      },
      "stockGraphs": [
        {
          "title": "Graph title",
          "valueField": "column-1"
        }
      ],
      "valueAxes": [
        {
          "title": "Axis title"
        }
      ],
      "legend": {
        "useGraphSettings": true
      },
      "titles": [
        {
          "size": 15,
          "text": "Chart Title"
        }
      ]
    }
  ]
});
```

You might find it useful to take a look at [our demos](https://www.amcharts.com/demos/intraday-data/), you can use the `View Demo Source` button in the lower-right corner to see the chart configuration that was used for that demo.

Also, you only need to add the `<script>` tags that you're actually using. So if you're not using `xy` charts, you don't need to include `xy.js`, and the same for the other chart types (since you're using a `stock` chart you must include `amcharts.js`, `serial.js`, and `amstock.js`).

**Comment by justinbleach** [comment]
@Pauan  I tried this and I am getting errors in the console:

d.clear is not a function
and
Cannot read property 'construct' of undefined

I've changed my imports to this:
`"scripts": [
        "../node_modules/amstock3/amcharts/amcharts.js",
        "../node_modules/amstock3/amcharts/amstock.js",
        "../node_modules/amstock3/amcharts/serial.js",    
        "../node_modules/amstock3/amcharts/themes/light.js",
        "../node_modules/amcharts3/amcharts/plugins/dataloader/dataloader.min.js"
      ]`

**Comment by justinbleach** [comment]
I added exports plugin and it's css but get the same error.

**Comment by justinbleach** [comment]
I've limited the problem down to a single error now:

TypeError: Cannot read property 'construct' of undefined
    at b.construct (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:20), <anonymous>:74:934)
    at new b (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:20), <anonymous>:1:391)
    at Object.d.processObject (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:20), <anonymous>:28:465)
    at b.addPanels (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:20), <anonymous>:24:205)
    at b.afterWrite (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:20), <anonymous>:7:298)
    at b.write (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:20), <anonymous>:4:101)
    at eval (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:20), <anonymous>:12:3)
    at d.handleLoad (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:20), <anonymous>:7:329)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192)

**Comment by Pauan** [comment]
@justinbleach I'm sorry for the delay. Could you please give me all of the code that you are using to create the chart?

**Comment by justinbleach** [comment]
@Pauan Here is my entire code.

Component: 

`import { Component, AfterViewInit, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { AmChartsService, AmChart } from "@amcharts/amcharts3-angular";

import { ManagerService } from '../../shared/manager.service';
import { DataSet } from '../../shared/amcharts/DataSet';

@Component({
    selector: 'status',
    templateUrl: './nodeStatusTab.component.html',
    styleUrls: ['./nodeStatusTab.component.css']
  })
export class NodeStatusTabComponent implements AfterViewInit, OnInit {

  statusAmChart:AmChart;

  constructor(private AmCharts: AmChartsService, private managerService: ManagerService, private route: ActivatedRoute) {}

  ngOnInit() {
        this.managerService.getDeviceStatus().subscribe(data => {this.deviceStatus = data});
        this.managerService.getNodeSummary().subscribe(data => {this.nodeSummary = data});
        this.route.params.subscribe(params => {
            this.selectedDevice = params['deviceId'];
        })


    }

    ngAfterViewInit() {
        this.managerService.getDeviceStatus().subscribe(data => {
            this.deviceStatus = data;
        });

       this.statusAmChart = this.AmCharts.makeChart("statusChartDiv",{
           "type": "stock",
           "dataSets": [
             {
               "fieldMappings": [
               {
                   "fromField": "column-1",
                   "toField": "column-1"
                 }
               ],
               "dataProvider": [
                 {
                   "category": "category 1",
                   "column-1": 8
                 },
                 {
                   "category": "category 2",
                   "column-1": 10
                 },
               ]
             }
           ],
           "panels": [
             {
               "categoryField": "category",
               "categoryAxis": {
                 "gridPosition": "start"
               },
               "stockGraphs": [
                 {
                   "title": "Graph title",
                   "valueField": "column-1"
                 }
               ],
               "valueAxes": [
                 {
                   "title": "Axis title"
                 }
               ],
               "legend": {
                 "useGraphSettings": true
               },
               "titles": [
                 {
                   "size": 15,
                   "text": "Chart Title"
                 }
               ]
             }
           ]
         });

    }`

View:
` <div class="container-fluid tab-section">
    <form class="form-inline">
	    <div class="input-group pad-right-3">
	       <span class="input-group-addon" id="startDateTime-addon1">From</span>
	       <p-calendar id="startDateTime" name="startDateTime" [(ngModel)]="startDateTime" showTime="true" [showIcon]="true" showButtonBar="true"></p-calendar>
	    </div>
	    <div class="input-group pad-right-3">
           <span class="input-group-addon" id="endDateTime-addon1">To</span>
           <p-calendar id="endDateTime" name="endDateTime" [(ngModel)]="endDateTime" showTime="true" [showIcon]="true" showButtonBar="true"></p-calendar>
        </div>
        <button type="submit" id="queryChart" class="queryChart"> 
            <span class="glyphicon glyphicon-ok"></span>
        </button>
    </form>
    
    <div id="statusChartDiv" [style.width.%]="100" [style.height.px]="500"></div>
    <div id="gballoon" style="display: none"></div>
</div>`

Here is the angular-cli.json:
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "manager-ui"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "stubs",
        "favicon.ico",
        "../node_modules/amstock3/amcharts/images",
        "../node_modules/amstock3/images"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "manager",
      "styles": [
        "../node_modules/font-awesome/css/font-awesome.min.css",
        "../node_modules/primeng/resources/themes/omega/theme.css",
        "../node_modules/primeng/resources/primeng.min.css",
        "../node_modules/amstock3/amcharts/plugins/export/export.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/amstock3/amcharts/amcharts.js",
        "../node_modules/amstock3/amcharts/amstock.js",
        "../node_modules/amstock3/amcharts/serial.js", 
        "../node_modules/amstock3/amcharts/plugins/export/export.min.js",   
        "../node_modules/amstock3/amcharts/themes/light.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "int": "environments/environment.int.ts",
        "qa": "environments/environment.qa.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}`

Let me know if you need anything else.

**Comment by justinbleach** [comment]
@Pauan got it to work by making sure serial.js was included in my angular-cli BEFORE amstock.js

Stupid mistake on my part.

**Comment by Pauan** [comment]
@justinbleach I'm glad you were able to get it working!

Feel free to contact us again if you have any further problems.

**Comment by jcmontx** [comment]
Hello guys, do you have a working example using amstock? It would be really useful.
