### ISSUE TITLE
Amcharts angular as part of webpack

### ISSUE THREAD

**Issue by UdayaBhandaru** [amcharts/amcharts3-angular2#66]
Using Amcharts angular as part of webpack.

I am Getting this error
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
     @ ./node_modules/@amcharts/amcharts3-angular/umd/index.js

**Comment by ryzy** [comment]
@UdayaBhandaru we'd need more data to help with these. The error message doesn't say anything about AmCharts - how do you know that's the one to blame?

Are you using it with angular-cli? It works out-of-the box, w/o any issues like the one you mentioned. What do you mean by _using Amcharts angular as part of webpack_?

**Comment by UdayaBhandaru** [comment]
Webpack is module binder. we are using Web pack in our project. When we are doing webpack we are getting this warning.

Attached are the webpack config , ts config and package.json and component files
[amcharts.component .html.txt](https://github.com/amcharts/amcharts3-angular2/files/1599540/amcharts.component.html.txt)
[amcharts.component .txt](https://github.com/amcharts/amcharts3-angular2/files/1599541/amcharts.component.txt)




[package.txt](https://github.com/amcharts/amcharts3-angular2/files/1599527/package.txt)
[tsconfig .txt](https://github.com/amcharts/amcharts3-angular2/files/1599528/tsconfig.txt)
[webpack.config .txt](https://github.com/amcharts/amcharts3-angular2/files/1599529/webpack.config.txt)
[webpack.config.vendor.txt](https://github.com/amcharts/amcharts3-angular2/files/1599530/webpack.config.vendor.txt)

**Comment by Pauan** [comment]
@UdayaBhandaru When using Webpack, it should automatically use the `es2015` code, but for an unknown reason it's not doing that for you.

So you can use `import { AmChartsService, AmChart } from '@amcharts/amcharts3-angular/es2015';` instead, which should fix the problem.
