### ISSUE TITLE
Dependencies not in the package

### ISSUE THREAD

**Issue by litenull** [amcharts/amcharts3-angular2#73]
Hello,

I'm wondering why are the dependencies not in the package. For example, it would be nice to import the charts directly in the component, instead of adding script tags before initialization.

Any ideas ?

**Comment by Pauan** [comment]
@litenull That's because AmCharts 3 was created a very long time ago, before npm even existed, so it is designed to be loaded with `<script>` tags.

We will soon release AmCharts 4, which will have excellent support for npm, Webpack, Angular, etc.
