### ISSUE TITLE
How do I use add / remove stock panels when using Angular 5

### ISSUE THREAD

**Issue by ravithb** [amcharts/amcharts3-angular2#82]
I'm using @amcharts/amcharts3-angular and I need to dynamically add / remove panels to a stock chart. 

I have looked at the documentation and even though there are functions addPanel() and removePanel(), I'm stuck trying to create the StockPanel and StockGraph objects dynamically, because the typescript doesn't seem to allow it. (i.e. these types doesn't seem to be exported in AmChartsService or AmCharts).

How do I do this?

**Comment by Pauan** [comment]
@ravithb Sorry for the delay! You're right, it doesn't seem possible right now. I'm looking into a fix for this ASAP.

**Comment by Pauan** [comment]
I just released `@amcharts/amcharts3-angular` version `2.2.0` which adds in `StockPanel` and `StockGraph` constructors, so now it's possible to use `new this.AmCharts.StockPanel()` and `new this.AmCharts.StockGraph()`
