### ISSUE TITLE
Gantt.js

### ISSUE THREAD

**Issue by alexdragneel** [amcharts/amcharts3-angular2#85]
Hello,

I want to use your plugin to do a Gantt chart I have this error: "b.AmGanttChart.base is undefined", have you an idea to fix it ?

Thank you :)

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **38569**.
> (replying here will automatically notify amCharts support agent)

Hi there,

Do you have gantt.js included in your index.html scripts? Note in our readme it mentions changing the script tags to correspond to the chart type you're using if you're not using serial.js (columns/lines):

```
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script> <!--base library for all chart types -->
<script src="https://www.amcharts.com/lib/3/gantt.js"></script>  <!-- gantt library -->
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script> <!-- optional light theme -->
```

Let me know if that helps.

Best,

Anthony Piris
amCharts

**Comment by alexdragneel** [comment]
Hello,
Yes, i have included it in the index.html the 3 lines and change the second one with gantt.
Maybe the variable chart (AmChart) need more information with the gantt that an serial ?

**Comment by alexdragneel** [comment]
It's working with a serial, but when I changed the script in index.html and the type of chart for gantt, I have the error.

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **38569**.
> (replying here will automatically notify amCharts support agent)

Hi there, 

My apologies, you need both serial and gantt in your includes to make gantt charts work. Sorry for the confusion. It should be:

```
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script> <!--base library for all chart types -->
<script src="https://www.amcharts.com/lib/3/serial.js"></script>  <!-- serial library -->
<script src="https://www.amcharts.com/lib/3/gantt.js"></script>  <!-- gantt library -->
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script> <!-- optional light theme -->
```

Note that the gantt chart structure is different from a serial chart, so I hope you're not just changing the type and are changing other properties as well (see our [gantt chart demo for more info](http://www.amcharts.com/demos/gantt-chart/); your last comment didn't mention this so I'm just making sure.

Let me know if adding serial back before gantt helps.

Best,

Anthony Piris
amCharts

**Comment by alexdragneel** [comment]
It's ok it's working, sorry to not see the 2 imports in the exemple 👍 
Thank you for the advice, I had already recovered the correct data structure :)

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **38569**.
> (replying here will automatically notify amCharts support agent)

You're welcome. No need to apologize, I missed the second import as well. :) Glad you were able to get it working!

Best,

Anthony Piris
amCharts
