### ISSUE TITLE
Is amCharts 3 officially supported for angular 6

### ISSUE THREAD

**Issue by lakshman53** [amcharts/amcharts3-angular2#91]
I am planning to upgrade my webapp using acharya to angular 6. I don't see any official documentation for Angular 6. I see for 2,3,4, and 5.

Is it in pipeline or the 2.x version of amcharts version is supported in 6 too.

**Comment by Pauan** [comment]
@lakshman53 Yes, it works with Angular 6. I've updated our README and example to use Angular 6.

**Comment by lakshman53** [comment]
Thank you
