### ISSUE TITLE
Releasing 2.2.3 on npm?

### ISSUE THREAD

**Issue by justinasit** [amcharts/amcharts3-angular2#95]
Hello,

It seems like the latest version on npm (https://www.npmjs.com/package/@amcharts/amcharts3-angular) is still 2.2.2. I can see you made updates for Angular 7 support in 2.2.3, but the package does not seem to have been updated on npm.

Thank you!

**Comment by martynasma** [comment]
Oops. Looks like we forgot to publish the latest release.

Published just now.

Thanks for the heads up!

**Comment by justinasit** [comment]
Perfect, appreciate it!
