### ISSUE TITLE
Gantt Chart segments do not have correct length, only less number of segments is displayed 

### ISSUE THREAD

**Issue by padmaruban** [amcharts/amcharts3-angular2#96]
Hi @amcharts .
I am using amchart3 gantt chart with angular 6. It is working fine for less number of segments and categories. I have data with more than 30 categories and segments in it. It is loading gantt chart incorrectly with less number of segments and these segments' length are not in correct size. Please help me to make this work correctly.

**Comment by martynasma** [comment]
Would you be able to post your chart config?

**Comment by padmaruban** [comment]
Hi @martynasma,
 Here is the sample data file with chart generation code for reference .

[support.zip](https://github.com/amcharts/amcharts3-angular2/files/2701559/support.zip)

Thanks in advance

**Comment by martynasma** [comment]
Thank you.

I'm trying to make a sense of your data. What `start` and `end` values are supposed to represent? Right now they are used as JavaSrtipt timestamps, which means number of milliseconds from 1970. Is that how you intended it to be used?

https://codepen.io/team/amcharts/pen/d994ec37a2962795c26fb61b29915436?editors=0010

**Comment by padmaruban** [comment]
Hi @martynasma 
Thanks for the reply.

I was trying with the  javascript timestamps in a straight way previuosly. It did not work in a way of displaying time at the X axis. Thats why I tried with converting them to minutes (javascript timestamp/ (60*1000)).
That **start** value is actually converted data as stated here.

**Comment by padmaruban** [comment]
> Thank you.
> 
> I'm trying to make a sense of your data. What `start` and `end` values are supposed to represent? Right now they are used as JavaSrtipt timestamps, which means number of milliseconds from 1970. Is that how you intended it to be used?
> 
> https://codepen.io/team/amcharts/pen/d994ec37a2962795c26fb61b29915436?editors=0010

Thanks, It displays all the segments when I use Javascript timestamps in **start** and **end** (I ignored **duration**) values. I could not make it to display time in X axis.

**Comment by padmaruban** [comment]
> Thank you.
> 
> I'm trying to make a sense of your data. What `start` and `end` values are supposed to represent? Right now they are used as JavaSrtipt timestamps, which means number of milliseconds from 1970. Is that how you intended it to be used?
> 
> https://codepen.io/team/amcharts/pen/d994ec37a2962795c26fb61b29915436?editors=0010


I have tried the following. 
1. changed **start** and **end** values in Javascript timestamps,
2. Ignored **duration** value
3. configuration changes 
    **{ "period": "fff" }**
It now displays all the segments, and time in X axis.

@martynasma 
Thank you very much for your support.
